name: Calibre News Delivery

on:
  schedule:
    # 每天北京时间 07:00（= UTC 23:00）自动跑
    - cron: '0 23 * * *'
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 0) 检出仓库
    - uses: actions/checkout@v4

    # 1) 还原增量状态缓存
    - name: Restore seen.json cache
      uses: actions/cache@v4
      with:
        path: state
        key: seen-json

    # 2) 安装运行脚本所需的 Python 包、Calibre CLI
    - name: Setup Calibre
      uses: robinhuettner/setup-calibre@v2

    # 3) 运行抓取 + 打包（ci.py 是模板仓库自带脚本）
    - name: Run Calibre News
      id: build
      run: |
        python ci.py

    # 4) 保存最新增量状态到缓存
    - name: Save seen.json cache
      if: steps.build.outcome == 'success'
      uses: actions/cache/save@v4
      with:
        path: state
        key: seen-json

    # 5) 下载并安装 rclone
    - name: Setup rclone
      uses: wei/rclone@v1
      with:
        rclone_conf: ${{ secrets.RCLONE_CONF }}

    # 6) 把 EPUB 复制到 OneDrive /CalibreNews
    - name: Copy EPUB to OneDrive
      if: steps.build.outcome == 'success' && steps.build.outputs.files != ''
      run: |
        rclone copy output/ onedrive:CalibreNews --create-dir --fast-list
