name: Calibre News Delivery

on:
  schedule:
    # 每日北京时间 07:00 (= UTC 23:00) 运行
    - cron:  '0 23 * * *'
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 0) 检出仓库
    - uses: actions/checkout@v4

    # 1) 还原增量缓存
    - uses: actions/cache@v4
      with:
        path: state
        key: seen-json

    # 2) 安装 Calibre CLI（官方 Ubuntu 源）
    - name: Install Calibre CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y calibre   # 提供 ebook-convert

    # 3) 运行抓取 + 打包
    - name: Build EPUB(s)
      run: |
        set -eo pipefail
        mkdir -p output
        while IFS=: read -r recipe outname; do
          echo "Convert $recipe -> $outname"
          set +e
          ebook-convert "$recipe" "output/$outname"
          code=$?
          set -e
          if [ "$code" -ne 0 ] && [ "$code" -ne 1 ]; then
            echo "::error ::ebook-convert exit $code"
            exit "$code"          # 仅非 0/1 时让 CI 失败
          fi
        done < recipe_list.txt



    # 4) 保存最新增量缓存
    - uses: actions/cache/save@v4
      if: steps.build.outcome == 'success'
      with:
        path: state
        key: seen-json

    # 5) 安装 rclone
    - uses: wei/rclone@v1
      with:
        rclone_conf: ${{ secrets.RCLONE_CONF }}

    # 6) 复制 EPUB 到 OneDrive
    - name: Copy EPUB to OneDrive
      if: success() && steps.build.outputs.files != ''
      run: |
        rclone copy output/ onedrive:CalibreNews --create-dir --fast-list
