name: Calibre News Delivery

on:
  schedule:
    # 每日北京时间 07:00 (= UTC 23:00) 运行
    - cron: '0 23 * * *'
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0) 检出仓库
      - uses: actions/checkout@v4

      # 0.5) 强制清空 state 目录，确保本次当作“第一次抓取”
      - name: Reset state dir
        run: |
          rm -rf state
          mkdir -p state
          echo "✅ state 目录已重置"

      # 1) 尝试恢复增量缓存
      - uses: actions/cache/restore@v4
        with:
          path: state
          key: seen-json

      # 2) 安装 Calibre
      - name: Install Calibre CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      # 3) 运行抓取 + 打包
      - name: Build EPUB(s)
        id: build-step
        run: |
          chmod +x build.sh
          ./build.sh

      # 3.5) 列出 state/ 目录和 seen.json，方便日志确认
      - name: Show state dir
        run: |
          echo "::group::state 内容"
          ls -lR state || true
          echo "::endgroup::"

      # 4) 保存最新增量缓存（只在 build 成功时）
      - uses: actions/cache/save@v4
        if: steps.build-step.outcome == 'success'
        with:
          path: state
          key: seen-json-${{ github.run_id }}

      # 5) 安装 rclone
      - name: Install rclone
        run: |
          sudo apt-get install -y rclone
      
      # 6) 输出 RCLONE_CONFIG 到文件
      - name: Write rclone.conf from secret
        run: |
          echo "$RCLONE_CONFIG" > rclone.conf
      
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      
      # 7) 打印前 10 行，调试用，可省略
      - name: Print rclone.conf (first 10 lines)
        run: head -10 rclone.conf
      
      # 8) 上传 EPUB 到 OneDrive
      - name: Copy EPUB to OneDrive
        if: success()
        run: |
          ls -l output || true
          rclone --config rclone.conf copy output/ myonedrive:CalibreNews --fast-list --verbose


